import { MemberDetailObj } from '@/types/constant/member'

export const memberMap: MemberDetailObj = new Map([
  [
    '上村莉菜',
    {
      name: '上村莉菜',
      birthday: '1997年1月4日',
      sign: 'やぎ座',
      height: '153.5cm',
      birthplace: '千葉県',
      bloodType: 'O型',
      src: '/assets/member_list/uemura.jpeg',
    },
  ],
  [
    '小池美波',
    {
      name: '小池美波',
      birthday: '1998年11月14日',
      sign: 'さそり座',
      height: '158.5cm',
      birthplace: '兵庫県',
      bloodType: 'B型',
      src: '/assets/member_list/koike.jpeg',
    },
  ],
  [
    '小林由依',
    {
      name: '小林由依',
      birthday: '1999年10月23日',
      sign: 'てんびん座',
      height: '161cm',
      birthplace: '埼玉県',
      bloodType: 'A型',
      src: '/assets/member_list/kobayashi.jpeg',
    },
  ],
  [
    '齋藤冬優花',
    {
      name: '齋藤冬優花',
      birthday: '1998年2月15日',
      sign: 'みずがめ座',
      height: '158cm',
      birthplace: '東京都',
      bloodType: 'O型',
      src: '/assets/member_list/saito.jpeg',
    },
  ],
  [
    '土生瑞穂',
    {
      name: '土生瑞穂',
      birthday: '1997年7月7日',
      sign: 'かに座',
      height: '171.6cm',
      birthplace: '東京都',
      bloodType: 'A型',
      sns: '',
      src: '/assets/member_list/habu.jpeg',
    },
  ],
  [
    '井上梨名',
    {
      name: '井上梨名',
      birthday: '2001年1月29日',
      sign: 'みずがめ座',
      height: '163cm',
      birthplace: '兵庫県',
      bloodType: 'A型',
      src: '/assets/member_list/inoue.jpeg',
    },
  ],
  [
    '遠藤光莉',
    {
      name: '遠藤光莉',
      birthday: '1999年2月15日',
      sign: 'おひつじ座',
      height: '164.5cm',
      birthplace: '神奈川県',
      bloodType: 'A型',
      src: '/assets/member_list/endo.jpeg',
    },
  ],
  [
    '大園玲',
    {
      name: '大園玲',
      birthday: '2000年4月18日',
      sign: 'おひつじ座',
      height: '158cm',
      birthplace: '鹿児島県',
      bloodType: 'A型',
      src: '/assets/member_list/ozno.jpeg',
    },
  ],
  [
    '大沼晶保',
    {
      name: '大沼晶保',
      birthday: '1999年10月12日',
      sign: 'てんびん座',
      height: '161cm',
      birthplace: '静岡県',
      bloodType: 'B型',
      src: '/assets/member_list/oonuma.jpeg',
    },
  ],
  [
    '幸阪茉里乃',
    {
      name: '幸阪茉里乃',
      birthday: '2002年12月19日',
      sign: 'いて座',
      height: '154.5cm',
      birthplace: '三重県',
      bloodType: 'O型',
      src: '/assets/member_list/kousaka.jpeg',
    },
  ],
  [
    '関有美子',
    {
      name: '関有美子',
      birthday: '1999年6月29日',
      sign: 'かに座',
      height: '167cm',
      birthplace: '静岡県',
      bloodType: 'A型',
      src: '/assets/member_list/seki.jpeg',
    },
  ],
  [
    '武元唯衣',
    {
      name: '武元唯衣',
      birthday: '2002年3月23日',
      sign: 'おひつじ座',
      height: '158.5cm',
      birthplace: '滋賀県',
      bloodType: 'O型',
      src: '/assets/member_list/takemoto.jpeg',
    },
  ],
  [
    '田村保乃',
    {
      name: '田村保乃',
      birthday: '1998年10月21日',
      sign: 'てんびん座',
      height: '163cm',
      birthplace: '大阪府',
      bloodType: 'A型',
      src: '/assets/member_list/tamura.jpeg',
    },
  ],
  [
    '藤吉夏鈴',
    {
      name: '藤吉夏鈴',
      birthday: '2001年8月29日',
      sign: 'おとめ座',
      height: '165.1cm',
      birthplace: '大阪府',
      bloodType: 'A型',
      src: '/assets/member_list/fujiyoshi.jpeg',
    },
  ],
  [
    '増本綺良',
    {
      name: '増本綺良',
      birthday: '2002年1月12日',
      sign: 'やぎ座',
      height: '158.4cm',
      birthplace: '兵庫県',
      bloodType: 'A型',
      src: '/assets/member_list/masumoto.jpeg',
    },
  ],
  [
    '松田里奈',
    {
      name: '松田里奈',
      birthday: '1999年10月13日',
      sign: 'てんびん座',
      height: '159.5cm',
      birthplace: '宮崎県',
      bloodType: 'O型',
      src: '/assets/member_list/matuda.jpeg',
    },
  ],
  [
    '森田ひかる',
    {
      name: '森田ひかる',
      birthday: '2001年7月10日',
      sign: 'かに座',
      height: '150.5cm',
      birthplace: '福岡県',
      bloodType: 'B型',
      src: '/assets/member_list/hikaru.jpeg',
    },
  ],
  [
    '守屋麗奈',
    {
      name: '守屋麗奈',
      birthday: '2000年1月2日',
      sign: 'やぎ座',
      height: '154cm',
      birthplace: '東京都',
      bloodType: 'AB型',
      src: '/assets/member_list/moriya.jpeg',
    },
  ],
  [
    '山﨑天',
    {
      name: '山崎天',
      birthday: '2005年9月28日',
      sign: 'てんびん座',
      height: '168.4cm',
      birthplace: '大阪府',
      bloodType: 'A型',
      src: '/assets/member_list/yamasaki.jpeg',
    },
  ],
])
