import { MemberDetailObj, MemberObj, MemberSrc } from '@/types/constant/member'

// トップページサイトでの使用 //
export const firstMemberSrc = [
  {
    src: '/assets/member/uemura_main_visual.jpeg',
    name: '上村莉菜',
    ruby: 'うえむらりな',
    birthday: '1997年1月4日',
    sign: 'やぎ座',
  },
  {
    src: '/assets/member/koike_main_visual.jpeg',
    name: '小池美波',
    ruby: 'こいけみなみ',
    birthday: '1998年11月14日',
    sign: 'さそり座',
  },
  {
    src: '/assets/member/kobayashi_main_visual.jpeg',
    name: '小林由依',
    ruby: 'こばやしゆい',
    birthday: '1999年10月23日',
    sign: 'てんびん座',
  },
  {
    src: '/assets/member/saito_main_visual.jpeg',
    name: '齋藤冬優花',
    ruby: 'さいとうふゆか',
    birthday: '1998年2月15日',
    sign: 'みずがめ座',
  },
  {
    src: '/assets/member/habu_main_visual.jpeg',
    name: '土生瑞穂',
    ruby: 'はぶみずほ',
    birthday: '1997年7月7日',
    sign: 'かに座',
  },
]
export const secondMemberSrc = [
  {
    src: '/assets/member/inoue_main_visual.jpeg',
    name: '井上梨名',
    ruby: 'いのうえりな',
    birthday: '2001年1月29日',
    sign: 'みずがめ座',
  },
  {
    src: '/assets/member/endo_main_visual.jpeg',
    name: '遠藤光莉',
    ruby: 'えんどうひかり',
    birthday: '1999年2月15日',
    sign: 'おひつじ座',
  },
  {
    src: '/assets/member/ozno_main_visual.jpeg',
    name: '大園玲',
    ruby: 'おおぞのれい',
    birthday: '2000年4月18日',
    sign: 'おひつじ座',
  },
  {
    src: '/assets/member/oonuma_main_visual.jpeg',
    name: '大沼晶保',
    ruby: 'おおぬまあきほ',
    birthday: '1999年10月12日',
    sign: 'てんびん座',
  },
  {
    src: '/assets/member/kousaka_main_visual.jpeg',
    name: '幸阪茉里乃',
    ruby: 'こうさかまりの',
    birthday: '2002年12月19日',
    sign: 'いて座',
  },
  {
    src: '/assets/member/seki_main_visual.jpeg',
    name: '関有美子',
    ruby: 'せきゆみこ',
    birthday: '1999年6月29日',
    sign: 'かに座',
  },
  {
    src: '/assets/member/takemoto_main_visual.jpeg',
    name: '武元唯衣',
    ruby: 'たけもとゆい',
    birthday: '2002年3月23日',
    sign: 'おひつじ座',
  },
  {
    src: '/assets/member/tamura_main_visual.jpeg',
    name: '田村保乃',
    ruby: 'たむらほの',
    birthday: '1998年10月21日',
    sign: 'てんびん座',
  },
  {
    src: '/assets/member/fujiyoshi_main_visual.jpeg',
    name: '藤吉夏鈴',
    ruby: 'ふじよしかりん',
    birthday: '2001年8月29日',
    sign: 'おとめ座',
  },
  {
    src: '/assets/member/matuda_main_visual.jpeg',
    name: '松田里奈',
    ruby: 'まつだりな',
    birthday: '1999年10月13日',
    sign: 'てんびん座',
  },
  {
    src: '/assets/member/masumoto_main_visual.jpeg',
    name: '増本綺良',
    ruby: 'ますもときら',
    birthday: '2002年1月12日',
    sign: 'やぎ座',
  },
  {
    src: '/assets/member/hikaru_main_visual.jpeg',
    name: '森田ひかる',
    ruby: 'もりたひかる',
    birthday: '2001年7月10日',
    sign: 'かに座',
  },
  {
    src: '/assets/member/moriya_main_visual.jpeg',
    name: '守屋麗奈',
    ruby: 'もりやれな',
    birthday: '2000年1月2日',
    sign: 'やぎ座',
  },
  {
    src: '/assets/member/yamasaki_main_visual.jpeg',
    name: '山﨑天',
    ruby: 'やまさきてん',
    birthday: '2005年9月28日',
    sign: 'てんびん座',
  },
]
export const thirdMemberSrc = [
  { src: '/assets/member_list/matono.jpeg', name: '的野美青' },
  { src: '/assets/member_list/kojima.jpeg', name: '小島凪紗' },
  { src: '/assets/member_list/nakajima.jpeg', name: '中嶋優月' },
  { src: '/assets/member_list/odakura.jpeg', name: '小田倉麗奈' },
  { src: '/assets/member_list/mukai.jpeg', name: '向井純葉' },
  { src: '/assets/member_list/riko.jpeg', name: '遠藤理子' },
  { src: '/assets/member_list/ishimori.jpeg', name: '石森璃花' },
  { src: '/assets/member_list/taniguti.jpeg', name: '谷口愛李' },
  { src: '/assets/member_list/murayama.jpeg', name: '村山美羽' },
  { src: '/assets/member/seki_main_visual.jpeg', name: 'Coming soon' },
  { src: '/assets/member/takemoto_main_visual.jpeg', name: 'Coming soon' },
]
// お気に入りメンバー決める //
export const favoriteMember: MemberSrc[] = [
  {
    src: 'uemura_main_visual.jpeg',
    name: '上村莉菜',
  },
  {
    src: 'koike_main_visual.jpeg',
    name: '小池美波',
  },
  {
    src: 'kobayashi_main_visual.jpeg',
    name: '小林由依',
  },
  {
    src: 'saito_main_visual.jpeg',
    name: '齋藤冬優花',
  },
  {
    src: 'habu_main_visual.jpeg',
    name: '土生瑞穂',
  },
  {
    src: 'inoue_main_visual.jpeg',
    name: '井上梨名',
  },
  {
    src: 'endo_main_visual.jpeg',
    name: '遠藤光莉',
  },
  {
    src: 'ozno_main_visual.jpeg',
    name: '大園玲',
  },
  {
    src: 'oonuma_main_visual.jpeg',
    name: '大沼晶保',
  },
  {
    src: 'kousaka_main_visual.jpeg',
    name: '幸阪茉里乃',
  },
  {
    src: 'seki_main_visual.jpeg',
    name: '関有美子',
  },
  {
    src: 'takemoto_main_visual.jpeg',
    name: '武元唯衣',
  },
  {
    src: 'tamura_main_visual.jpeg',
    name: '田村保乃',
  },
  {
    src: 'fujiyoshi_main_visual.jpeg',
    name: '藤吉夏鈴',
  },
  {
    src: 'matuda_main_visual.jpeg',
    name: '松田里奈',
  },
  {
    src: 'masumoto_main_visual.jpeg',
    name: '増本綺良',
  },
  {
    src: 'hikaru_main_visual.jpeg',
    name: '森田ひかる',
  },
  {
    src: 'moriya_main_visual.jpeg',
    name: '守屋麗奈',
  },
  {
    src: 'yamasaki_main_visual.jpeg',
    name: '山﨑天',
  },
]
export const memberSrc: MemberObj[] = [
  {
    src: '/assets/member/uemura_main_visual.jpeg',
    name: '上村莉菜',
    ruby: 'うえむらりな',
    birthday: '1997年1月4日',
    sign: 'やぎ座',
  },
  {
    src: '/assets/member/koike_main_visual.jpeg',
    name: '小池美波',
    ruby: 'こいけみなみ',
    birthday: '1998年11月14日',
    sign: 'さそり座',
  },
  {
    src: '/assets/member/kobayashi_main_visual.jpeg',
    name: '小林由依',
    ruby: 'こばやしゆい',
    birthday: '1999年10月23日',
    sign: 'てんびん座',
  },
  {
    src: '/assets/member/saito_main_visual.jpeg',
    name: '齋藤冬優花',
    ruby: 'さいとうふゆか',
    birthday: '1998年2月15日',
    sign: 'みずがめ座',
  },
  {
    src: '/assets/member/habu_main_visual.jpeg',
    name: '土生瑞穂',
    ruby: 'はぶみずほ',
    birthday: '1997年7月7日',
    sign: 'かに座',
  },
  {
    src: '/assets/member/inoue_main_visual.jpeg',
    name: '井上梨名',
    ruby: 'いのうえりな',
    birthday: '2001年1月29日',
    sign: 'みずがめ座',
  },
  {
    src: '/assets/member/endo_main_visual.jpeg',
    name: '遠藤光莉',
    ruby: 'えんどうひかり',
    birthday: '1999年2月15日',
    sign: 'おひつじ座',
  },
  {
    src: '/assets/member/ozno_main_visual.jpeg',
    name: '大園玲',
    ruby: 'おおぞのれい',
    birthday: '2000年4月18日',
    sign: 'おひつじ座',
  },
  {
    src: '/assets/member/oonuma_main_visual.jpeg',
    name: '大沼晶保',
    ruby: 'おおぬまあきほ',
    birthday: '1999年10月12日',
    sign: 'てんびん座',
  },
  {
    src: '/assets/member/kousaka_main_visual.jpeg',
    name: '幸阪茉里乃',
    ruby: 'こうさかまりの',
    birthday: '2002年12月19日',
    sign: 'いて座',
  },
  {
    src: '/assets/member/seki_main_visual.jpeg',
    name: '関有美子',
    ruby: 'せきゆみこ',
    birthday: '1999年6月29日',
    sign: 'かに座',
  },
  {
    src: '/assets/member/takemoto_main_visual.jpeg',
    name: '武元唯衣',
    ruby: 'たけもとゆい',
    birthday: '2002年3月23日',
    sign: 'おひつじ座',
  },
  {
    src: '/assets/member/tamura_main_visual.jpeg',
    name: '田村保乃',
    ruby: 'たむらほの',
    birthday: '1998年10月21日',
    sign: 'てんびん座',
  },
  {
    src: '/assets/member/fujiyoshi_main_visual.jpeg',
    name: '藤吉夏鈴',
    ruby: 'ふじよしかりん',
    birthday: '2001年8月29日',
    sign: 'おとめ座',
  },
  {
    src: '/assets/member/matuda_main_visual.jpeg',
    name: '松田里奈',
    ruby: 'まつだりな',
    birthday: '1999年10月13日',
    sign: 'てんびん座',
  },
  {
    src: '/assets/member/masumoto_main_visual.jpeg',
    name: '増本綺良',
    ruby: 'ますもときら',
    birthday: '2002年1月12日',
    sign: 'やぎ座',
  },
  {
    src: '/assets/member/hikaru_main_visual.jpeg',
    name: '森田ひかる',
    ruby: 'もりたひかる',
    birthday: '2001年7月10日',
    sign: 'かに座',
  },
  {
    src: '/assets/member/moriya_main_visual.jpeg',
    name: '守屋麗奈',
    ruby: 'もりやれな',
    birthday: '2000年1月2日',
    sign: 'やぎ座',
  },
  {
    src: '/assets/member/yamasaki_main_visual.jpeg',
    name: '山﨑天',
    ruby: 'やまさきてん',
    birthday: '2005年9月28日',
    sign: 'てんびん座',
  },
]
export const memberSrcMap = new Map([
  ['上村莉菜', { src: 'uemura_main_visual.jpeg', name: '上村莉菜' }],
  ['小池美波', { src: 'koike_main_visual.jpeg', name: '小池美波' }],
  ['小林由依', { src: 'kobayashi_main_visual.jpeg', name: '小林由依' }],
  ['齋藤冬優花', { src: 'saito_main_visual.jpeg', name: '齋藤冬優花' }],
  ['土生瑞穂', { src: 'habu_main_visual.jpeg', name: '土生瑞穂' }],
  ['井上梨名', { src: 'inoue_main_visual.jpeg', name: '井上梨名' }],
  ['遠藤光莉', { src: 'endo_main_visual.jpeg', name: '遠藤光莉' }],
  ['大園玲', { src: 'ozno_main_visual.jpeg', name: '大園玲' }],
  ['大沼晶保', { src: 'oonuma_main_visual.jpeg', name: '大沼晶保' }],
  ['幸阪茉里乃', { src: 'kousaka_main_visual.jpeg', name: '幸阪茉里乃' }],
  ['関有美子', { src: 'seki_main_visual.jpeg', name: '関有美子' }],
  ['武元唯衣', { src: 'takemoto_main_visual.jpeg', name: '武元唯衣' }],
  ['田村保乃', { src: 'tamura_main_visual.jpeg', name: '田村保乃' }],
  ['藤吉夏鈴', { src: 'fujiyoshi_main_visual.jpeg', name: '藤吉夏鈴' }],
  ['松田里奈', { src: 'matuda_main_visual.jpeg', name: '松田里奈' }],
  ['増本綺良', { src: 'masumoto_main_visual.jpeg', name: '増本綺良' }],
  ['森田ひかる', { src: 'hikaru_main_visual.jpeg', name: '森田ひかる' }],
  ['守屋麗奈', { src: 'moriya_main_visual.jpeg', name: '守屋麗奈' }],
  ['山﨑天', { src: 'yamasaki_main_visual.jpeg', name: '山﨑天' }],
])
