export const memberMap = new Map([
  [
    '上村莉奈',
    {
      name: '上村莉奈',
      age: 25,
      birthday: '1997年1月4日',
      sign: 'やぎ座',
      height: '153.5cm',
      birthplace: '千葉県',
      bloodType: 'O型',
    },
  ],
  [
    '小池美波',
    {
      name: '小池美波',
      age: 24,
      birthday: '1998年11月14日',
      sign: 'さそり座',
      height: '158.5cm',
      birthplace: '兵庫県',
      bloodType: 'B型',
    },
  ],
  [
    '小林由依',
    {
      name: '小林由依',
      age: 23,
      birthday: '1999年10月23日',
      sign: 'てんびん座',
      height: '161cm',
      birthplace: '埼玉県',
      bloodType: 'A型',
    },
  ],
  [
    '齋藤冬優花',
    {
      name: '齋藤冬優花',
      age: 24,
      birthday: '1998年2月15日',
      sign: 'みずがめ座',
      height: '158cm',
      birthplace: '東京都',
      bloodType: 'O型',
    },
  ],
  [
    '土生瑞穂',
    {
      name: '土生瑞穂',
      age: 25,
      birthday: '1997年7月7日',
      sign: 'かに座',
      height: '171.6cm',
      birthplace: '東京都',
      bloodType: 'A型',
      sns: '',
    },
  ],
  [
    '井上梨名',
    {
      name: '井上梨名',
      age: 21,
      birthday: '2001年1月29日',
      sign: 'みずがめ座',
      height: '163cm',
      birthplace: '兵庫県',
      bloodType: 'A型',
    },
  ],
  [
    '遠藤光莉',
    {
      name: '遠藤光莉',
      age: 23,
      birthday: '1999年2月15日',
      sign: 'おひつじ座',
      height: '164.5cm',
      birthplace: '神奈川県',
      bloodType: 'A型',
    },
  ],
  [
    '大園玲',
    {
      name: '大園玲',
      age: 22,
      birthday: '2000年4月18日',
      sign: 'おひつじ座',
      height: '158cm',
      birthplace: '鹿児島県',
      bloodType: 'A型',
    },
  ],
  [
    '大沼晶保',
    {
      name: '大沼晶保',
      age: 24,
      birthday: '1999年10月12日',
      sign: 'てんびん座',
      height: '161cm',
      birthplace: '静岡県',
      bloodType: 'B型',
    },
  ],
  [
    '幸阪茉里乃',
    {
      name: '幸阪茉里乃',
      age: 20,
      birthday: '2002年12月19日',
      sign: 'いて座',
      height: '154.5cm',
      birthplace: '三重県',
      bloodType: 'O型',
    },
  ],
  [
    '関有美子',
    {
      name: '関有美子',
      age: 24,
      birthday: '1999年6月29日',
      sign: 'かに座',
      height: '167cm',
      birthplace: '静岡県',
      bloodType: 'A型',
    },
  ],
  [
    '武元唯衣',
    {
      name: '武元唯衣',
      age: 20,
      birthday: '2002年3月23日',
      sign: 'おひつじ座',
      height: '158.5cm',
      birthplace: '滋賀県',
      bloodType: 'O型',
    },
  ],
  [
    '田村保乃',
    {
      name: '田村保乃',
      age: 24,
      birthday: '1998年10月21日',
      sign: 'てんびん座',
      height: '163cm',
      birthplace: '大阪府',
      bloodType: 'A型',
    },
  ],
  [
    '藤吉夏鈴',
    {
      name: '藤吉夏鈴',
      age: 21,
      birthday: '2001年8月29日',
      sign: 'おとめ座',
      height: '165.1cm',
      birthplace: '大阪府',
      bloodType: 'A型',
    },
  ],
  [
    '増本綺良',
    {
      name: '増本綺良',
      age: 20,
      birthday: '2002年1月12日',
      sign: 'やぎ座',
      height: '158.4cm',
      birthplace: '兵庫県',
      bloodType: 'A型',
    },
  ],
  [
    '松田里奈',
    {
      name: '松田里奈',
      age: 23,
      birthday: '1999年10月13日',
      sign: 'てんびん座',
      height: '159.5cm',
      birthplace: '宮崎県',
      bloodType: 'O型',
    },
  ],
  [
    '森田ひかる',
    {
      name: '森田ひかる',
      age: 21,
      birthday: '2001年7月10日',
      sign: 'かに座',
      height: '150.5cm',
      birthplace: '福岡県',
      bloodType: 'B型',
    },
  ],
  [
    '守屋麗奈',
    {
      name: '守屋麗奈',
      age: 22,
      birthday: '2000年1月2日',
      sign: 'やぎ座',
      height: '154cm',
      birthplace: '東京都',
      bloodType: 'AB型',
    },
  ],
  [
    '山﨑天',
    {
      name: '山崎天',
      age: 17,
      birthday: '2005年9月28日',
      sign: 'てんびん座',
      height: '168.4cm',
      birthplace: '大阪府',
      bloodType: 'A型',
    },
  ],
])
