export const memberSrc = [
  { src: '/assets/member/uemura_main_visual.jpeg', name: '上村莉奈' },
  { src: '/assets/member/koike_main_visual.jpeg', name: '小池美波' },
  { src: '/assets/member/kobayashi_main_visual.jpeg', name: '小林由依' },
  { src: '/assets/member/saito_main_visual.jpeg', name: '齋藤冬優花' },
  { src: '/assets/member/habu_main_visual.jpeg', name: '土生瑞穂' },
  { src: '/assets/member/inoue_main_visual.jpeg', name: '井上梨名' },
  { src: '/assets/member/endo_main_visual.jpeg', name: '遠藤光莉' },
  { src: '/assets/member/ozno_main_visual.jpeg', name: '大園玲' },
  { src: '/assets/member/seki_main_visual.jpeg', name: '関有美子' },
  { src: '/assets/member/takemoto_main_visual.jpeg', name: '武元唯衣' },
  { src: '/assets/member/tamura_main_visual.jpeg', name: '田村保乃' },
  { src: '/assets/member/fujiyoshi_main_visual.jpeg', name: '藤吉夏鈴' },
  { src: '/assets/member/matuda_main_visual.jpeg', name: '松田里奈' },
  { src: '/assets/member/masumoto_main_visual.jpeg', name: '増本綺良' },
  { src: '/assets/member/hikaru_main_visual.jpeg', name: '森田ひかる' },
  { src: '/assets/member/moriya_main_visual.jpeg', name: '守屋麗奈' },
  { src: '/assets/member/yamasaki_main_visual.jpeg', name: '山﨑天' },
]

export const memberSrcMap = new Map([
  ['上村莉奈', { src: 'uemura_main_visual.jpeg', name: '上村莉奈' }],
  ['小池美波', { src: 'koike_main_visual.jpeg', name: '小池美波' }],
  ['小林由依', { src: 'kobayashi_main_visual.jpeg', name: '小林由依' }],
  ['齋藤冬優花', { src: 'saito_main_visual.jpeg', name: '齋藤冬優花' }],
  ['土生瑞穂', { src: 'habu_main_visual.jpeg', name: '土生瑞穂' }],
  ['井上梨名', { src: 'inoue_main_visual.jpeg', name: '井上梨名' }],
  ['遠藤光莉', { src: 'endo_main_visual.jpeg', name: '遠藤光莉' }],
  ['大園玲', { src: 'ozno_main_visual.jpeg', name: '大園玲' }],
  ['関有美子', { src: 'seki_main_visual.jpeg', name: '関有美子' }],
  ['武元唯衣', { src: 'takemoto_main_visual.jpeg', name: '武元唯衣' }],
  ['田村保乃', { src: 'tamura_main_visual.jpeg', name: '田村保乃' }],
  ['藤吉夏鈴', { src: 'fujiyoshi_main_visual.jpeg', name: '藤吉夏鈴' }],
  ['松田里奈', { src: 'matuda_main_visual.jpeg', name: '松田里奈' }],
  ['増本綺良', { src: 'masumoto_main_visual.jpeg', name: '増本綺良' }],
  ['森田ひかる', { src: 'hikaru_main_visual.jpeg', name: '森田ひかる' }],
  ['守屋麗奈', { src: 'moriya_main_visual.jpeg', name: '守屋麗奈' }],
  ['山﨑天', { src: 'yamasaki_main_visual.jpeg', name: '山﨑天' }],
])
